In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os
import pandas as pd
import numpy as np

In [3]:
base_folder = "/content/drive/MyDrive/aiassignment3"
print(os.listdir(base_folder))

['CrimeReport (1).txt', '911-calls-wav2vec2.ipynb', '911_calls_analysis.csv', 'LESO2.pdf', 'student2_mixed_pdf_analysis.csv', 'student2.ipynb', 'student3_final_output.csv', 'student3.ipynb', 'Walk1.mpg', 'Browse2.mpg', 'Rest_InChair.mpg', 'Rest_FallOnFloor.mpg', 'LeftBox.mpg', 'student4_event_log.csv', 'student4.ipynb', 'student5_output.csv', 'student5.ipynb', 'finalintegration.ipynb']

In [4]:
audio_df = pd.read_csv(f"{base_folder}/911_calls_analysis.csv")
pdf_df   = pd.read_csv(f"{base_folder}/student2_mixed_pdf_analysis.csv")
image_df = pd.read_csv(f"{base_folder}/student3_final_output.csv")
video_df = pd.read_csv(f"{base_folder}/student4_event_log.csv")
text_df  = pd.read_csv(f"{base_folder}/student5_output.csv")

print("Audio shape:", audio_df.shape)
print("PDF shape:", pdf_df.shape)
print("Image shape:", image_df.shape)
print("Video shape:", video_df.shape)
print("Text shape:", text_df.shape)

Audio shape: (3, 6)
PDF shape: (61, 8)
Image shape: (154, 5)
Video shape: (27, 6)
Text shape: (115, 6)

In [5]:
print("Audio columns:", audio_df.columns.tolist())
print("PDF columns:", pdf_df.columns.tolist())
print("Image columns:", image_df.columns.tolist())
print("Video columns:", video_df.columns.tolist())
print("Text columns:", text_df.columns.tolist())

Audio columns: ['Call_ID', 'Transcript', 'Extracted_Event', 'Location', 'Sentiment', 'Urgency_Score']
PDF columns: ['Report_ID', 'Start_Page', 'End_Page', 'Department', 'Doc_Type', 'Date', 'Program', 'Key_Detail']
Image columns: ['Image_ID', 'Scene_Type', 'Objects_Detected', 'Bounding_Boxes', 'Confidence']
Video columns: ['Clip_ID', 'Timestamp', 'Frame_ID', 'Event_Detected', 'Persons_Count', 'Confidence']
Text columns: ['Text_ID', 'Crime_Type', 'Location_Entity', 'Sentiment', 'Topic', 'Severity_Label']

In [6]:
audio_clean = audio_df[["Extracted_Event"]].copy()
audio_clean.columns = ["Audio_Event"]

pdf_clean = pdf_df[["Doc_Type"]].copy()
pdf_clean.columns = ["PDF_Doc_Type"]

image_clean = image_df[["Objects_Detected"]].copy()
image_clean.columns = ["Image_Objects"]

video_clean = video_df[["Event_Detected"]].copy()
video_clean.columns = ["Video_Event"]

text_clean = text_df[["Crime_Type"]].copy()
text_clean.columns = ["Text_Crime_Type"]

In [7]:
max_len = max(
    len(audio_clean),
    len(pdf_clean),
    len(image_clean),
    len(video_clean),
    len(text_clean)
)

print("Max rows:", max_len)

Max rows: 154

In [8]:
audio_clean = audio_clean.reindex(range(max_len))
pdf_clean   = pdf_clean.reindex(range(max_len))
image_clean = image_clean.reindex(range(max_len))
video_clean = video_clean.reindex(range(max_len))
text_clean  = text_clean.reindex(range(max_len))

In [9]:
incident_ids = [f"INC_{i+1:03}" for i in range(max_len)]

In [10]:
final_df = pd.DataFrame({
    "Incident_ID": incident_ids,
    "Audio_Event": audio_clean["Audio_Event"],
    "PDF_Doc_Type": pdf_clean["PDF_Doc_Type"],
    "Image_Objects": image_clean["Image_Objects"],
    "Video_Event": video_clean["Video_Event"],
    "Text_Crime_Type": text_clean["Text_Crime_Type"]
})

final_df.head(20)

,Incident_ID,Audio_Event,PDF_Doc_Type,Image_Objects,Video_Event,Text_Crime_Type
0,INC_001,Shooting / active shooter,Training Document,fire,Person Running,Disturbance
1,INC_002,Shooting / active shooter,MRAP Operations,fire,Person Sitting,Disturbance
2,INC_003,Shooting / active shooter,Not found,NaN,Person Running,Disturbance
3,INC_004,NaN,Lesson Plan,fire,Person Walking,Disturbance
4,INC_005,NaN,Training Document,"fire, smoke",Person Sitting,Murder
5,INC_006,NaN,Training Document,smoke,Person Sitting,Disturbance
6,INC_007,NaN,Training Document,fire,Person Running,Robbery
7,INC_008,NaN,Not found,fire,Person Sitting,Disturbance
8,INC_009,NaN,Training Document,fire,Person Walking,Disturbance
9,INC_010,NaN,Not found,NaN,Person Sitting,Disturbance
10,INC_011,NaN,Training Document,fire,Person Walking,Theft
11,INC_012,NaN,Training Document,fire,Person Walking,Disturbance
12,INC_013,NaN,Training Document,smoke,Person Sitting,Disturbance
13,INC_014,NaN,Training Document,fire,Person Walking,Disturbance
14,INC_015,NaN,MRAP Operations,fire,Person Collapsing,Disturbance
15,INC_016,NaN,Not found,smoke,Person Running,Disturbance
16,INC_017,NaN,Training Document,fire,Person Walking,Disturbance
17,INC_018,NaN,Training Document,fire,Person Sitting,Disturbance
18,INC_019,NaN,MRAP Operations,fire,Person Sitting,Disturbance
19,INC_020,NaN,MRAP Operations,fire,Person Sitting,Disturbance

In [11]:
final_df = final_df.fillna("Not Available")
final_df.head(20)

,Incident_ID,Audio_Event,PDF_Doc_Type,Image_Objects,Video_Event,Text_Crime_Type
0,INC_001,Shooting / active shooter,Training Document,fire,Person Running,Disturbance
1,INC_002,Shooting / active shooter,MRAP Operations,fire,Person Sitting,Disturbance
2,INC_003,Shooting / active shooter,Not found,Not Available,Person Running,Disturbance
3,INC_004,Not Available,Lesson Plan,fire,Person Walking,Disturbance
4,INC_005,Not Available,Training Document,"fire, smoke",Person Sitting,Murder
5,INC_006,Not Available,Training Document,smoke,Person Sitting,Disturbance
6,INC_007,Not Available,Training Document,fire,Person Running,Robbery
7,INC_008,Not Available,Not found,fire,Person Sitting,Disturbance
8,INC_009,Not Available,Training Document,fire,Person Walking,Disturbance
9,INC_010,Not Available,Not found,Not Available,Person Sitting,Disturbance
10,INC_011,Not Available,Training Document,fire,Person Walking,Theft
11,INC_012,Not Available,Training Document,fire,Person Walking,Disturbance
12,INC_013,Not Available,Training Document,smoke,Person Sitting,Disturbance
13,INC_014,Not Available,Training Document,fire,Person Walking,Disturbance
14,INC_015,Not Available,MRAP Operations,fire,Person Collapsing,Disturbance
15,INC_016,Not Available,Not found,smoke,Person Running,Disturbance
16,INC_017,Not Available,Training Document,fire,Person Walking,Disturbance
17,INC_018,Not Available,Training Document,fire,Person Sitting,Disturbance
18,INC_019,Not Available,MRAP Operations,fire,Person Sitting,Disturbance
19,INC_020,Not Available,MRAP Operations,fire,Person Sitting,Disturbance

In [12]:
def compute_severity(row):
    text_val = str(row["Text_Crime_Type"]).lower()
    audio_val = str(row["Audio_Event"]).lower()
    image_val = str(row["Image_Objects"]).lower()
    video_val = str(row["Video_Event"]).lower()
    pdf_val = str(row["PDF_Doc_Type"]).lower()

    high_keywords = [
        "murder", "robbery", "assault", "fire", "shooting",
        "collapse", "collapsing", "fight", "fighting", "trapped"
    ]

    medium_keywords = [
        "theft", "accident", "disturbance", "vehicle", "smoke",
        "burglary", "fraud", "person movement"
    ]

    combined = " ".join([text_val, audio_val, image_val, video_val, pdf_val])

    if any(word in combined for word in high_keywords):
        return "High"
    elif any(word in combined for word in medium_keywords):
        return "Medium"
    else:
        return "Low"

In [13]:
final_df["Severity"] = final_df.apply(compute_severity, axis=1)
final_df.head(20)

,Incident_ID,Audio_Event,PDF_Doc_Type,Image_Objects,Video_Event,Text_Crime_Type,Severity
0,INC_001,Shooting / active shooter,Training Document,fire,Person Running,Disturbance,High
1,INC_002,Shooting / active shooter,MRAP Operations,fire,Person Sitting,Disturbance,High
2,INC_003,Shooting / active shooter,Not found,Not Available,Person Running,Disturbance,High
3,INC_004,Not Available,Lesson Plan,fire,Person Walking,Disturbance,High
4,INC_005,Not Available,Training Document,"fire, smoke",Person Sitting,Murder,High
5,INC_006,Not Available,Training Document,smoke,Person Sitting,Disturbance,Medium
6,INC_007,Not Available,Training Document,fire,Person Running,Robbery,High
7,INC_008,Not Available,Not found,fire,Person Sitting,Disturbance,High
8,INC_009,Not Available,Training Document,fire,Person Walking,Disturbance,High
9,INC_010,Not Available,Not found,Not Available,Person Sitting,Disturbance,Medium
10,INC_011,Not Available,Training Document,fire,Person Walking,Theft,High
11,INC_012,Not Available,Training Document,fire,Person Walking,Disturbance,High
12,INC_013,Not Available,Training Document,smoke,Person Sitting,Disturbance,Medium
13,INC_014,Not Available,Training Document,fire,Person Walking,Disturbance,High
14,INC_015,Not Available,MRAP Operations,fire,Person Collapsing,Disturbance,High
15,INC_016,Not Available,Not found,smoke,Person Running,Disturbance,Medium
16,INC_017,Not Available,Training Document,fire,Person Walking,Disturbance,High
17,INC_018,Not Available,Training Document,fire,Person Sitting,Disturbance,High
18,INC_019,Not Available,MRAP Operations,fire,Person Sitting,Disturbance,High
19,INC_020,Not Available,MRAP Operations,fire,Person Sitting,Disturbance,High

In [14]:
print(final_df.to_string(index=False))

Incident_ID               Audio_Event                 PDF_Doc_Type Image_Objects       Video_Event Text_Crime_Type Severity
    INC_001 Shooting / active shooter            Training Document          fire    Person Running     Disturbance     High
    INC_002 Shooting / active shooter              MRAP Operations          fire    Person Sitting     Disturbance     High
    INC_003 Shooting / active shooter                    Not found Not Available    Person Running     Disturbance     High
    INC_004             Not Available                  Lesson Plan          fire    Person Walking     Disturbance     High
    INC_005             Not Available            Training Document   fire, smoke    Person Sitting          Murder     High
    INC_006             Not Available            Training Document         smoke    Person Sitting     Disturbance   Medium
    INC_007             Not Available            Training Document          fire    Person Running         Robbery     High
    INC_008             Not Available                    Not found          fire    Person Sitting     Disturbance     High
    INC_009             Not Available            Training Document          fire    Person Walking     Disturbance     High
    INC_010             Not Available                    Not found Not Available    Person Sitting     Disturbance   Medium
    INC_011             Not Available            Training Document          fire    Person Walking           Theft     High
    INC_012             Not Available            Training Document          fire    Person Walking     Disturbance     High
    INC_013             Not Available            Training Document         smoke    Person Sitting     Disturbance   Medium
    INC_014             Not Available            Training Document          fire    Person Walking     Disturbance     High
    INC_015             Not Available              MRAP Operations          fire Person Collapsing     Disturbance     High
    INC_016             Not Available                    Not found         smoke    Person Running     Disturbance   Medium
    INC_017             Not Available            Training Document          fire    Person Walking     Disturbance     High
    INC_018             Not Available            Training Document          fire    Person Sitting     Disturbance     High
    INC_019             Not Available              MRAP Operations          fire    Person Sitting     Disturbance     High
    INC_020             Not Available              MRAP Operations          fire    Person Sitting     Disturbance     High
    INC_021             Not Available            Training Document         smoke    Person Sitting     Disturbance   Medium
    INC_022             Not Available            Training Document Not Available    Person Running     Disturbance   Medium
    INC_023             Not Available            Training Document          fire    Person Running     Disturbance     High
    INC_024             Not Available Standard Operating Procedure Not Available    Person Running     Disturbance   Medium
    INC_025             Not Available            Training Document         smoke    Person Running     Disturbance   Medium
    INC_026             Not Available          Operating Procedure          fire    Person Sitting           Theft     High
    INC_027             Not Available                    Not found          fire    Person Sitting     Disturbance     High
    INC_028             Not Available                       Report          fire     Not Available     Disturbance     High
    INC_029             Not Available                    Not found         smoke     Not Available     Disturbance   Medium
    INC_030             Not Available            Training Document         smoke     Not Available     Disturbance   Medium
    INC_031             Not Available                    Not found         smoke     Not Available            Fire     High
    INC_032             Not Available                    Not found          fire     Not Available     Disturbance     High
    INC_033             Not Available                       Report          fire     Not Available     Disturbance     High
    INC_034             Not Available                    Not found          fire     Not Available     Disturbance     High
    INC_035             Not Available                    Not found          fire     Not Available     Disturbance     High
    INC_036             Not Available                    Not found         smoke     Not Available     Disturbance   Medium
    INC_037             Not Available                    Not found         smoke     Not Available           Fraud   Medium
    INC_038             Not Available                    Not found          fire     Not Available     Disturbance     High
    INC_039             Not Available                    Not found Not Available     Not Available     Disturbance   Medium
    INC_040             Not Available            Training Document          fire     Not Available     Disturbance     High
    INC_041             Not Available            Training Document          fire     Not Available     Disturbance     High
    INC_042             Not Available            Training Document          fire     Not Available     Disturbance     High
    INC_043             Not Available            Training Document          fire     Not Available           Fraud     High
    INC_044             Not Available            Training Document          fire     Not Available         Assault     High
    INC_045             Not Available                    Not found          fire     Not Available     Disturbance     High
    INC_046             Not Available                    Not found          fire     Not Available         Assault     High
    INC_047             Not Available                    Not found          fire     Not Available     Disturbance     High
    INC_048             Not Available                    Not found          fire     Not Available          Murder     High
    INC_049             Not Available                Training Plan Not Available     Not Available           Fraud   Medium
    INC_050             Not Available                    Not found          fire     Not Available     Disturbance     High
    INC_051             Not Available                    Not found         smoke     Not Available           Fraud   Medium
    INC_052             Not Available            Training Document          fire     Not Available     Disturbance     High
    INC_053             Not Available            Training Document          fire     Not Available     Disturbance     High
    INC_054             Not Available            Training Document         smoke     Not Available     Disturbance   Medium
    INC_055             Not Available                    Not found         smoke     Not Available     Disturbance   Medium
    INC_056             Not Available            Training Document         smoke     Not Available     Disturbance   Medium
    INC_057             Not Available            Training Document          fire     Not Available     Disturbance     High
    INC_058             Not Available            Training Document   fire, smoke     Not Available           Fraud     High
    INC_059             Not Available                    Not found          fire     Not Available     Disturbance     High
    INC_060             Not Available            Training Document         smoke     Not Available     Disturbance   Medium
    INC_061             Not Available                    Not found         smoke     Not Available     Disturbance   Medium
    INC_062             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_063             Not Available                Not Available Not Available     Not Available     Disturbance   Medium
    INC_064             Not Available                Not Available Not Available     Not Available     Disturbance   Medium
    INC_065             Not Available                Not Available          fire     Not Available          Murder     High
    INC_066             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_067             Not Available                Not Available   fire, smoke     Not Available     Disturbance     High
    INC_068             Not Available                Not Available Not Available     Not Available     Disturbance   Medium
    INC_069             Not Available                Not Available Not Available     Not Available     Disturbance   Medium
    INC_070             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_071             Not Available                Not Available         smoke     Not Available     Disturbance   Medium
    INC_072             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_073             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_074             Not Available                Not Available         smoke     Not Available     Disturbance   Medium
    INC_075             Not Available                Not Available         smoke     Not Available     Disturbance   Medium
    INC_076             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_077             Not Available                Not Available Not Available     Not Available     Disturbance   Medium
    INC_078             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_079             Not Available                Not Available Not Available     Not Available     Disturbance   Medium
    INC_080             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_081             Not Available                Not Available Not Available     Not Available     Disturbance   Medium
    INC_082             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_083             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_084             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_085             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_086             Not Available                Not Available Not Available     Not Available     Disturbance   Medium
    INC_087             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_088             Not Available                Not Available         smoke     Not Available     Disturbance   Medium
    INC_089             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_090             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_091             Not Available                Not Available         smoke     Not Available     Disturbance   Medium
    INC_092             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_093             Not Available                Not Available         smoke     Not Available     Disturbance   Medium
    INC_094             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_095             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_096             Not Available                Not Available         smoke     Not Available     Disturbance   Medium
    INC_097             Not Available                Not Available Not Available     Not Available     Disturbance   Medium
    INC_098             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_099             Not Available                Not Available          fire     Not Available           Fraud     High
    INC_100             Not Available                Not Available         smoke     Not Available     Disturbance   Medium
    INC_101             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_102             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_103             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_104             Not Available                Not Available          fire     Not Available          Murder     High
    INC_105             Not Available                Not Available   fire, smoke     Not Available         Assault     High
    INC_106             Not Available                Not Available          fire     Not Available         Assault     High
    INC_107             Not Available                Not Available         smoke     Not Available         Assault     High
    INC_108             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_109             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_110             Not Available                Not Available         smoke     Not Available     Disturbance   Medium
    INC_111             Not Available                Not Available Not Available     Not Available     Disturbance   Medium
    INC_112             Not Available                Not Available         smoke     Not Available     Disturbance   Medium
    INC_113             Not Available                Not Available          fire     Not Available         Assault     High
    INC_114             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_115             Not Available                Not Available          fire     Not Available     Disturbance     High
    INC_116             Not Available                Not Available          fire     Not Available   Not Available     High
    INC_117             Not Available                Not Available Not Available     Not Available   Not Available      Low
    INC_118             Not Available                Not Available          fire     Not Available   Not Available     High
    INC_119             Not Available                Not Available         smoke     Not Available   Not Available   Medium
    INC_120             Not Available                Not Available         smoke     Not Available   Not Available   Medium
    INC_121             Not Available                Not Available Not Available     Not Available   Not Available      Low
    INC_122             Not Available                Not Available          fire     Not Available   Not Available     High
    INC_123             Not Available                Not Available Not Available     Not Available   Not Available      Low
    INC_124             Not Available                Not Available         smoke     Not Available   Not Available   Medium
    INC_125             Not Available                Not Available          fire     Not Available   Not Available     High
    INC_126             Not Available                Not Available         smoke     Not Available   Not Available   Medium
    INC_127             Not Available                Not Available          fire     Not Available   Not Available     High
    INC_128             Not Available                Not Available          fire     Not Available   Not Available     High
    INC_129             Not Available                Not Available Not Available     Not Available   Not Available      Low
    INC_130             Not Available                Not Available Not Available     Not Available   Not Available      Low
    INC_131             Not Available                Not Available Not Available     Not Available   Not Available      Low
    INC_132             Not Available                Not Available         smoke     Not Available   Not Available   Medium
    INC_133             Not Available                Not Available          fire     Not Available   Not Available     High
    INC_134             Not Available                Not Available Not Available     Not Available   Not Available      Low
    INC_135             Not Available                Not Available   fire, smoke     Not Available   Not Available     High
    INC_136             Not Available                Not Available         smoke     Not Available   Not Available   Medium
    INC_137             Not Available                Not Available          fire     Not Available   Not Available     High
    INC_138             Not Available                Not Available          fire     Not Available   Not Available     High
    INC_139             Not Available                Not Available Not Available     Not Available   Not Available      Low
    INC_140             Not Available                Not Available         smoke     Not Available   Not Available   Medium
    INC_141             Not Available                Not Available         smoke     Not Available   Not Available   Medium
    INC_142             Not Available                Not Available Not Available     Not Available   Not Available      Low
    INC_143             Not Available                Not Available         smoke     Not Available   Not Available   Medium
    INC_144             Not Available                Not Available          fire     Not Available   Not Available     High
    INC_145             Not Available                Not Available          fire     Not Available   Not Available     High
    INC_146             Not Available                Not Available          fire     Not Available   Not Available     High
    INC_147             Not Available                Not Available         smoke     Not Available   Not Available   Medium
    INC_148             Not Available                Not Available         smoke     Not Available   Not Available   Medium
    INC_149             Not Available                Not Available          fire     Not Available   Not Available     High
    INC_150             Not Available                Not Available          fire     Not Available   Not Available     High
    INC_151             Not Available                Not Available         smoke     Not Available   Not Available   Medium
    INC_152             Not Available                Not Available          fire     Not Available   Not Available     High
    INC_153             Not Available                Not Available          fire     Not Available   Not Available     High
    INC_154             Not Available                Not Available Not Available     Not Available   Not Available      Low

In [15]:
output_path = f"{base_folder}/final_integrated_incident_dataset.csv"
final_df.to_csv(output_path, index=False)

print("Saved final integrated dataset to:", output_path)

Saved final integrated dataset to: /content/drive/MyDrive/aiassignment3/final_integrated_incident_dataset.csv